---
- name: Create a new host or update an existing host's info
  local_action:
    module: zabbix_host
    server_url: https://monitoring.shifteo.com/zabbix/
    login_user: ansible
    login_password: Rootmouad1
    host_name: "{{ ansible_fqdn }}"
    visible_name: "{{ ansible_fqdn }}"
    description: "{{ ansible_fqdn }}"

    host_groups:
      - Linux servers
    link_templates:
      - Template OS Linux
    interfaces:
        - type: 1
          main: 1
          useip: 1
          ip: "{{ansible_default_ipv4.address}}"
          dns: ""
          port: 10050
    status: enabled
    state: present
